name: Compilar Painel VIP OB52
on: 
  push:
    branches: [ main ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout do cÃ³digo
        uses: actions/checkout@v4

      - name: Instalar Theos e Dependencias
        run: |
          # Instala ldid para evitar o erro 127
          brew install ldid
          git clone --recursive https://github.com/theos/theos.git ~/theos
          echo "THEOS=~/theos" >> $GITHUB_ENV

      - name: Instalar SDK iOS
        run: |
          mkdir -p ~/theos/sdks
          curl -L https://github.com/theos/sdks/archive/master.zip -o sdks.zip
          unzip -q sdks.zip
          mv sdks-master/iPhoneOS14.5.sdk ~/theos/sdks/
          rm -rf sdks.zip sdks-master

      - name: Compilar o Painel (.dylib)
        run: |
          export THEOS=~/theos
          # FINALPACKAGE=1 e codesign skip para garantir a dylib limpa
          make package FINALPACKAGE=1 CODESIGN_IPA=0
          
      - name: Entregar Ficheiro Pronto
        uses: actions/upload-artifact@v4
        with:
          name: Painel_Final_Download
          path: packages/*.deb
