name: Compilar Painel VIP OB52
on: 
  push:
    branches: [ main ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout do seu codigo
        uses: actions/checkout@v4 # Atualizado para v4

      - name: Instalar Theos (Compilador)
        run: |
          export THEOS=~/theos
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos)"
          # Baixar SDKs essenciais para nao dar erro de falta de ficheiros
          curl -ksSL https://github.com/theos/sdks/raw/master/iPhoneOS14.5.sdk.tar.xz | tar -xf - -C $THEOS/sdks/
          echo "THEOS=$THEOS" >> $GITHUB_ENV

      - name: Compilar o Painel (.dylib)
        run: |
          export THEOS=~/theos
          make package FINALPACKAGE=1
          
      - name: Entregar Ficheiro Pronto
        uses: actions/upload-artifact@v4 # AQUI ESTAVA O ERRO, AGORA EST√Å EM V4
        with:
          name: Painel_Final_Download
          path: packages/*.deb
