name: Compilar Painel VIP OB52
on: 
  push:
    branches: [ main ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Theos Manualmente
        run: |
          git clone --recursive https://github.com/theos/theos.git ~/theos
          echo "THEOS=~/theos" >> $GITHUB_ENV

      - name: Instalar SDK iOS (Correção do Erro)
        run: |
          # Criamos a pasta de SDKs e baixamos diretamente sem usar o instalador do theos
          mkdir -p ~/theos/sdks
          curl -ksSL https://github.com/theos/sdks/raw/master/iPhoneOS14.5.sdk.tar.xz | tar -xf - -C ~/theos/sdks/

      - name: Compilar o Painel (.dylib)
        run: |
          export THEOS=~/theos
          # Forçamos a compilação limpa
          make package FINALPACKAGE=1
          
      - name: Entregar Ficheiro Pronto
        uses: actions/upload-artifact@v4
        with:
          name: Painel_Final_Download
          path: packages/*.deb
